print("load building.lua success")
function pathFindingInit(self)
    print("[pathFindingInit]start")
    local board = seekConfig(self,-1)
    addVoxel(board,0,0,0)
    local board = seekConfig(self,-2)
    addVoxel(board,0,0,0)
    local board = seekConfig(self,-3)
    addVoxel(board,0,0,0)
    local board = seekConfig(self,-4)
    addVoxel(board,0,0,0)
    local board = seekConfig(self,-5)
    addVoxel(board,0,0,0)
    local board = seekConfig(self,-6)
    addVoxel(board,0,0,0)
end
